name: CI/CD for Next.js (Frontend & Backend)

on:
  push:
    branches:
      - main # Runs on pushes to 'main'
  pull_request:
    branches:
      - main # Runs on PRs to 'main'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm" # Caches node_modules for faster builds

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      # - name: Run Tests
      #   run: npm test

  # deploy:
  #   needs: build_and_test # Only deploy if tests pass
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Deploy to Vercel
  #       run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
